apiVersion: v1
data:
  payout-account-mnemonic: {{ b64enc .Values.payout_account_mnemonic }}
  slack-alert-token: {{ b64enc .Values.slack_alert_token }}
kind: Secret
metadata:
  name: polkadot-payout-secrets
  namespace: {{ .Release.Namespace }}
