apiVersion: v1
data:
  proxy-account-mnemonic: {{ b64enc .Values.proxy_account_mnemonic }}
  slack-alert-token: {{ b64enc .Values.slack_alert_token }}
kind: Secret
metadata:
  name: polkadot-proxy-secrets
  namespace: {{ .Release.Namespace }}
