language: c

dist: trusty

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      sudo: false
    - os: linux
      sudo: false
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - bsdtar
      - g++-multilib
      - gcc-multilib
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils
      - rpm
      - xz-utils

before_install:
  - rm -rf ~/.nvm
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull && /tmp/git-lfs/git-lfs clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh && nvm install 8
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn install

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run build:travis-mac; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run build:travis-linux; fi

branches:
  only:
    - master
