environment:
  matrix:
    - nodejs_version: 8

platform:
  - x64

clone_depth: 5

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn\cache'

init:
  - cmd: git config --global core.autocrlf input

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - SET CI=true
  - SET PATH=%cd%\node_modules\.bin;%PATH%
  - yarn install

build_script:
  - yarn run build:appveyor

test: off

version: "1.0-{build}"

branches:
  only:
    - master
